# Generated by Django 5.1.2 on 2024-10-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key='bid', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
